Исправление ошибок и улучшение описания
MoreliaTalk/morelia_website pull request #1
Opened 2022-01-20 17:03 UTC by stepanskryabin

сабж.

2022-01-20 17:16 UTC, NekrodNIK requested changes

2022-01-20 17:16 UTC, NekrodNIK commented on pages/about.tsx
> +                            Сервер и клиенты можно использовать как встраиваемое решение для быстрого встраивания функционала
Тавтология тут. Встраивомое для встраивания

2022-01-20 17:16 UTC, NekrodNIK commented on pages/about.tsx
> +                                <li>дать пользователю право настроить какими данными он хочет делится</li>
право настроить... право настраивать лучше

2022-01-20 17:16 UTC, NekrodNIK commented on pages/index.tsx
> +                            <p>Благодаря полному шифрованию всех сообщений в чатах, доступ к вашим сообщениям имете лишь вы и те кому вы доверяете.
респект за это. что-то я даже не додумался до такого...

2022-01-20 17:16 UTC, NekrodNIK commented on pages/index.tsx
> +                                ЛЮБОЙ человек может изучить исходные тексты MoreliaTalk. Или, если захочет, даже поучавствовать
И, если захочет. Так куда лучше воспринимается

2022-01-20 17:16 UTC, NekrodNIK commented on pages/index.tsx
> +                                в его разработке или создать свой мессенджер на основа MoreliaTalk.
основе

2022-01-20 17:16 UTC, NekrodNIK commented on pages/index.tsx
> +                                Сервер и часть библиотеки лицензированы по LGPL v3.0, клиенты - по GPL v3.0.
библиотек

2022-01-20 17:16 UTC, NekrodNIK commented on pages/index.tsx
> +                                возможность быстрого внедрения разнообразных фишек, которые отсутвуют в других мессенджерах.
ну или так)))

2022-01-20 17:16 UTC, NekrodNIK commented on pages/about.tsx
> +                                    Stepan Skriabin
Опять с фамилией накосячил я...

2022-01-20 17:17 UTC, stepanskryabin commented on pages/about.tsx
> +                            Сервер и клиенты можно использовать как встраиваемое решение для быстрого встраивания функционала
да, поправлю

2022-01-20 17:19 UTC, stepanskryabin commented on pages/index.tsx
> +                                в его разработке или создать свой мессенджер на основа MoreliaTalk.
ок, поправлю

2022-01-20 17:19 UTC, stepanskryabin commented on pages/index.tsx
> +                                Сервер и часть библиотеки лицензированы по LGPL v3.0, клиенты - по GPL v3.0.
ок, поправлю

2022-01-20 17:20 UTC, stepanskryabin commented on pages/about.tsx
> +                                    Stepan Skriabin
с тебя исправление багов в сервере :laughing:

2022-01-20 17:21 UTC, stepanskryabin commented on pages/about.tsx
> +                                <li>дать пользователю право настроить какими данными он хочет делится</li>
ок, поправлю

2022-01-20 17:22 UTC, NekrodNIK commented on pages/index.tsx
> +                                ЛЮБОЙ человек может изучить исходные тексты MoreliaTalk. Или, если захочет, даже поучавствовать
Надо как-то по-другому написать.

2022-01-20 17:23 UTC, stepanskryabin commented on pages/index.tsx
> +                                в его разработке или создать свой мессенджер на основа MoreliaTalk.
не понял где менять это слово?

2022-01-20 17:24 UTC, NekrodNIK commented on pages/about.tsx
> +                                    Stepan Skriabin
Это я и так сделаю. Однако сначала надо бы пару мелких изменений перед релизом 0.0.1 внести. Нет, не в код, там для автоматических тестов на гитхабе. Просто потом когда мы ещё ихенения в мастер вносить будем? Вот имено, что не скоро

2022-01-20 17:26 UTC, NekrodNIK requested changes

2022-01-20 17:26 UTC, NekrodNIK commented on pages/about.tsx
> +                            современного чата (Slack, Telegram или WatsApp) в своём проекте, так и в личных целях.
очепятка в названии WhatsApp

2022-01-20 17:30 UTC, stepanskryabin commented on pages/about.tsx
> +                            современного чата (Slack, Telegram или WatsApp) в своём проекте, так и в личных целях.
исправил

2022-01-20 17:58 UTC, stepanskryabin commented on pages/index.tsx
> +                                ЛЮБОЙ человек может изучить исходные тексты MoreliaTalk. Или, если захочет, даже поучавствовать
ладно исправлю на ",а если захочет

2022-01-21 04:48 UTC, NekrodNIK commented on pages/index.tsx
> +                                в его разработке или создать свой мессенджер на основа MoreliaTalk.
На основе MoreliaTalk

2022-01-21 04:49 UTC, NekrodNIK commented on pages/about.tsx
> +                                    Stepan Skriabin
Хотя ладно, это оставлю на релиз 0.1.1

2022-01-21 17:12 UTC, stepanskryabin commented on pages/about.tsx
> +                                    Stepan Skriabin
ну ты блин нашел куда писать, надо про такое в чат))

2022-01-21 17:12 UTC, stepanskryabin commented
Я вроде всё поправил, принимай давай уже!

2022-01-22 04:31 UTC, NekrodNIK commented
> Я вроде всё поправил, принимай давай уже!

хехе)))

2022-01-22 04:33 UTC, NekrodNIK approved these changes

2022-01-22 04:33 UTC, merged